### ISSUE TITLE
Chat context issues

### ISSUE THREAD

**Issue by LukeMauldin** [CopilotC-Nvim/CopilotChat.nvim#702] opened 2024-12-29 22:07 UTC
I am using CopilotChat with Neovim 0.10.3 on OSX using lazy vim .  As soon as I enter insert mode and type `#`, it auto completes `#buffer` and even if I try to backspace and type `#file`, once again, `#buffer` is typed and then `file` is typed after it.  See the screenshot.

```
CopilotChat: require("CopilotChat.health").check()

CopilotChat.nvim ~
- If you are facing any issues, also see :CopilotChatDebugInfo for more information.

CopilotChat.nvim [core] ~
- OK nvim: NVIM v0.10.3
  Build type: Release
  LuaJIT 2.1.1734355927
  Run ":verbose version" for more info

CopilotChat.nvim [commands] ~
- OK curl: curl 8.7.1 (x86_64-apple-darwin24.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.63.0
  Release-Date: 2024-03-27
  Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
  Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe UnixSockets
- OK git: git version 2.47.1
- WARNING lynx: missing, optional for improved fetching of url contents. See "https://lynx.invisible-island.net/".

CopilotChat.nvim [dependencies] ~
- OK plenary: installed
- OK copilot: copilot.vim
- WARNING tiktoken_core: missing, optional for accurate token counting. See README for installation instructions.
- OK treesitter[markdown]: installed
- OK treesitter[diff]: installed


```

<img width="739" alt="image" src="https://github.com/user-attachments/assets/a770ca5c-5ce8-4ed8-8401-ceee7d52ab0d" />

**Comment by nyanyacoffee** [comment] 2024-12-30 23:15
In the README.md, it is mentioned:

> [!WARNING]  
> If you are on neovim < 0.11.0, you also might want to add `noinsert` and `popup` to your `completeopt` to make the chat completion behave well.

You need to add the following to your `init.lua`:
`vim.opt.completeopt = { "menuone", "popup", "noinsert" }`

**Comment by deathbeam** [comment] 2024-12-31 09:18
Duplicate of #691

**Closed by deathbeam** 2024-12-31 09:18 UTC

**Comment by LukeMauldin** [comment] 2024-12-31 15:01
I have that option set and I am still seeing the behavior.  Config:

```
    config = function()
      -- See `:help cmp`
      local cmp = require 'cmp'
      local luasnip = require 'luasnip'
      luasnip.config.setup {}

      cmp.setup {
        snippet = {
          expand = function(args)
            luasnip.lsp_expand(args.body)
          end,
        },
        completion = { completeopt = 'menuone,noinsert,popup' },

        -- For an understanding of why these mappings were
        -- chosen, you will need to read `:help ins-completion`
        --
        -- No, but seriously. Please read `:help ins-completion`, it is really good!
        mapping = cmp.mapping.preset.insert {
          -- Select the [n]ext item
          ['<C-n>'] = cmp.mapping.select_next_item(),
          -- Select the [p]revious item
          ['<C-p>'] = cmp.mapping.select_prev_item(),

          -- Scroll the documentation window [b]ack / [f]orward
          ['<C-b>'] = cmp.mapping.scroll_docs(-4),
          ['<C-f>'] = cmp.mapping.scroll_docs(4),

          -- Accept ([y]es) the completion.
          --  This will auto-import if your LSP supports it.
          --  This will expand snippets if the LSP sent a snippet.
          ['<C-y>'] = cmp.mapping.confirm { select = true },

          -- If you prefer more traditional completion keymaps,
          -- you can uncomment the following lines
          --['<CR>'] = cmp.mapping.confirm { select = true },
          --['<Tab>'] = cmp.mapping.select_next_item(),
          --['<S-Tab>'] = cmp.mapping.select_prev_item(),

          -- Manually trigger a completion from nvim-cmp.
          --  Generally you don't need this, because nvim-cmp will display
          --  completions whenever it has completion options available.
          ['<C-Space>'] = cmp.mapping.complete {},

          -- Think of <c-l> as moving to the right of your snippet expansion.
          --  So if you have a snippet that's like:
          --  function $name($args)
          --    $body
          --  end
          --
          -- <c-l> will move you to the right of each of the expansion locations.
          -- <c-h> is similar, except moving you backwards.
          ['<C-l>'] = cmp.mapping(function()
            if luasnip.expand_or_locally_jumpable() then
              luasnip.expand_or_jump()
            end
          end, { 'i', 's' }),
          ['<C-h>'] = cmp.mapping(function()
            if luasnip.locally_jumpable(-1) then
              luasnip.jump(-1)
            end
          end, { 'i', 's' }),

          -- For more advanced Luasnip keymaps (e.g. selecting choice nodes, expansion) see:
          --    https://github.com/L3MON4D3/LuaSnip?tab=readme-ov-file#keymaps
        },
        sources = {
          {
            name = 'lazydev',
            -- set group index to 0 to skip loading LuaLS completions as lazydev recommends it
            group_index = 0,
          },
          { name = 'nvim_lsp' },
          { name = 'luasnip' },
          { name = 'path' },
        },
      }
    end,

```

**Comment by LukeMauldin** [comment] 2024-12-31 15:06
Full config: https://github.com/LukeMauldin/nvim-config

**Comment by deathbeam** [comment] 2024-12-31 17:28
no idea wht the completion config does in nvim-cmp but try doing it with normal neovim config option.

**Comment by LukeMauldin** [comment] 2024-12-31 17:29
I am relatively new to neovim, is there some part that you would recommend me commenting out to start troubleshooting?  Could I exclude the Copilot Chat from using the normal neovim completion?

**Comment by deathbeam** [comment] 2024-12-31 17:35
well this is for example how I have my completeopt set:

```
vim.o.completeopt = 'menuone,noinsert,popup'
```

i dont use lazy.nvim or nvim-cmp (as neither is useful for me) so i dont really know how they operate

**Comment by lukemauldinks** [comment] 2024-12-31 23:35
Does you use blink for completion or no external completion framework?

**Comment by deathbeam** [comment] 2024-12-31 23:49
i just use something i wrote for myself (and only reason why i even use it is just for treesitter autocomplete when i dont have lsp): https://github.com/deathbeam/autocomplete.nvim
