### ISSUE TITLE
Error: Unsupported operating system

### ISSUE THREAD

**Issue by searleser97** [CopilotC-Nvim/CopilotChat.nvim#687] opened 2024-12-11 22:41 UTC
I am getting the following error when trying to update with lazy.nvim (using Windows)

![image](https://github.com/user-attachments/assets/1165e4ce-20c3-4378-a28b-8032b9287b47)

**Comment by deathbeam** [comment] 2024-12-11 22:53
Remove `make tiktoken` from your config, otherwise duplicate of #397

**Closed by deathbeam** 2024-12-11 22:53 UTC
