### ISSUE TITLE
Treesitter errors

### ISSUE THREAD

**Issue by omarabid** [CopilotC-Nvim/CopilotChat.nvim#653] opened 2024-11-30 11:35 UTC
I keep getting these treesitter errors everytime I post some non-conventional code

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 20:2. Invalid node type "luacode_environment":
(luacode_environment
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:128: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:511: in function 'add_child'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:395: in function '_add_injections'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:447: in function 'parse'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:460: in function 'parse'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:404: in function </usr/sh
```

how to disable treesitter altogether?

**Comment by deathbeam** [comment] 2024-11-30 11:51
cant you just do `:TSDisable highlight`?

Also could you show the code that causes this? And thats submitting that code to chat right?

**Comment by omarabid** [comment] 2024-11-30 11:56
That's what I do but I usually forget and then bam it completely blocks my editor

```scss
.notification :global(.cds--inline-notification) {
  margin: 0;
  max-width: 100%;
  box-shadow: none;
  margin-bottom: 0;
  margin-top: 0;
}

.notification :global(.cds--inline-notification__content p) {
  @include type-style('body-short-01');
}

.notification :global(.cds--inline-notification__content .cds--row) {
  margin: 0;
}

// Fix for notifications in lists
li .notification {
  flex: 0 0 100%;
  max-width: 100%;
}

// Remove this when Notifications are fixed upstream
.darkMode {
  background: $background-inverse !important;
  color: $text-on-color;
}
```

**Comment by deathbeam** [comment] 2024-11-30 12:05
Hmm, cant reproduce the error. Does it happen when using that code as selection, or when just pasting it to chat or in some of the overlay windows (like info/context)?

**Comment by deathbeam** [comment] 2024-11-30 12:06
Also what is your neovim version, maybe its happening on release only so i can chek that too I guess

**Comment by omarabid** [comment] 2024-11-30 12:46
It happens on Paste in the chat window.

NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by deathbeam** [comment] 2024-11-30 14:42
Hmm, cant reproduce on 0.10.2 either. But you can maybe try this:

```lua
vim.treesitter.language.register('off', { 'copilot-chat', 'copilot-diff', 'copilot-overlay' })
```

**Comment by deathbeam** [comment] 2024-12-01 12:32
Yea just tested it and that should work so closing, as the other issue sounds like upstream treesitter bug

**Closed by deathbeam** 2024-12-01 12:32 UTC
Labels: question
