### ISSUE TITLE
Expected value but found invalid token at character 1

### ISSUE THREAD

**Issue by thomastthai** [CopilotC-Nvim/CopilotChat.nvim#436] opened 2024-10-29 22:15 UTC
My setup with CopilotChat worked for weeks until a few days ago when the error, `Expected value but found invalid token at character 1` showed up. Lazy did two updates before the errors showed. Could this be related to #419 or #415?

The entire buffer was selected and `:'<,'>CopilotChatFix check errors` was executed that generated that error.  Similar CopilotChat commands showed the same error.

nvim's `:messages` command showed:

```
...
[CopilotChat.nvim]       TaskNode(
[CopilotChat.nvim]         id: Editor.createNodeId(),
[CopilotChat.nvim]         isComplete: true,
[CopilotChat.nvim]         text: AttributedText(
[CopilotChat.nvim]           'This is a completed task',
[CopilotChat.nvim]         ),
[CopilotChat.nvim]       ),
[CopilotChat.nvim]     ],
[CopilotChat.nvim]   );
[CopilotChat.nvim] }
[CopilotChat.nvim] [DEBUG 14:48:27] /Users/thomas/.local/share/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/copilot.lua:369: Model: gpt-4o-2024-05-13
[CopilotChat.nvim] [DEBUG 14:48:27] /Users/thomas/.local/share/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/copilot.lua:370: Temperature: 0.1
[CopilotChat.nvim] [ERROR 14:48:28] /Users/thomas/.local/share/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/copilot.lua:481: Failed parse response:
[CopilotChat.nvim] Unprocessable Entity
[CopilotChat.nvim] "Expected value but found invalid token at character 1"
```

The same error occurred using different models from the nvim command, `:CopilotChatModels`.

`CopilotChat in IDE` is enabled in my GitHub Copilot [settings](https://github.com/settings/copilot). This has not changed since I installed CopilotChat.

Removing `/Users/thomas/.local/share/nvim/lazy/CopilotChat.nvim/` and having `CopilotChat.nvim` reinstalled didn't address the error.

**Comment by gptlang** [comment] 2024-10-29 23:04
Hmm they might be running experiments with a different API. Check `/home/acheong/.local/state/nvim/CopilotChat.nvim.log` and see what the response was.

**Comment by deathbeam** [comment] 2024-10-30 10:14
I improved the error logging so can you check again now and check the error?

**Comment by deathbeam** [comment] 2024-10-30 10:14
Actually first lets just unify the issues, duplicate of #415 

Please dont open duplicates

**Closed by deathbeam** 2024-10-30 10:14 UTC
