### ISSUE TITLE
curl: (23) Failed writing received data to disk/application

### ISSUE THREAD

**Issue by Elyviere** [CopilotC-Nvim/CopilotChat.nvim#411] opened 2024-09-16 09:29 UTC
Hi.

I've just activated the copilot-chat plugin in LazyVim. After toggling the copilot chat and entering any text, I'm always met with the same error message:

```
Failed to get response: {
  exit = 23,
  message = 'get https://api.github.com/copilot_internal/v2/token - curl error exit_code=23 stderr={ "curl: (23) Failed writing received data to disk/application" }',
  stderr = '{ "curl: (23) Failed writing received data to disk/application" }'
}
```

Running `:Copilot auth` gives a message saying "Authenticated as Github user...", so I'm fairly sure I've done the necessary setup for this to work. I also couldn't find any issues relating to this exact issue, although there were a few curl-related ones, none referred to exit code 23.

![image](https://github.com/user-attachments/assets/548675f5-7d6c-46e6-98b3-6355d9b7eff3)

**Comment by gptlang** [comment] 2024-09-16 16:53
Duplicate of #380

**Closed by gptlang** 2024-09-16 16:53 UTC
