### ISSUE TITLE
Changed behavior in custom commands interaction after v3.2.0

### ISSUE THREAD

**Issue by nyanyacoffee** [CopilotC-Nvim/CopilotChat.nvim#676] opened 2024-12-05 07:40 UTC
### Description
I noticed a behavior change in command functionality when using the reference configuration from the official documentation:

```lua
vim.api.nvim_create_user_command("CopilotChatVisual", function(args)
  require("CopilotChat").ask(args.args, { selection = require("CopilotChat.select").visual })
end, { nargs = "*", range = true })

vim.api.nvim_create_user_command("CopilotChatBuffer", function(args)
  require("CopilotChat").ask(args.args, { selection = require("CopilotChat.select").buffer })
end, { nargs = "*", range = true })

vim.api.nvim_create_user_command("CopilotChatInline", function(args)
  require("CopilotChat").ask(args.args, {
    selection = require("CopilotChat.select").visual,
    window = {
      layout = "float",
      relative = "cursor",
      width = 1,
      height = 0.4,
      row = 1,
    },
  })
end, { nargs = "*", range = true })
```

> https://github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua

Since v3.2.0, these commands only work when providing immediate arguments. Previously, we could:
1. Execute commands without arguments (e.g., `:CopilotChatVisual`)
2. Input our requests in the chat panel
3. The buffer/selection content would be included automatically

### Expected Behavior
The commands should work as they did before v3.2.0, allowing for interactive usage through the chat panel without requiring immediate arguments.

### Current Behavior
- Commands only include buffer content when arguments are provided directly
  (e.g., `:CopilotChatVisual explain this code`)
  - Even with arguments provided, if you change the selection after running the command,
    the new selection won't be included in the context
- Cannot receive buffer content after execution without arguments
### Additional Context
The issue is most apparent when the parameter `selection` is set to `false`, but it seems that other configuration options also exhibit the same problem.

**Comment by deathbeam** [comment] 2024-12-05 08:03
I just tried all 3 commands you posted and I cant reproduce this behaviour at all.

If you set selection to false then you are disabling selection for the chat and so it obviously wont work.

You can check your current selection with `gc` so are you sure its not working.

**Comment by nyanyacoffee** [comment] 2024-12-05 09:18
https://github.com/user-attachments/assets/e5ad1669-8b5d-43e0-b471-f2753e81056b

nvim 0.10.2

Minimal Configuration
```lua
return {
  "CopilotC-Nvim/CopilotChat.nvim",
  branch = "main",
  -- version = 'v3.1.0',
  dependencies = {
    "zbirenbaum/copilot.lua",
    "nvim-lua/plenary.nvim",
  },
  build = "make tiktoken",
  event = "VeryLazy",
  config = function()
    require("CopilotChat").setup({
      model = "claude-3.5-sonnet",
      selection = false,
    })
    vim.api.nvim_create_user_command("CopilotChatVisual", function(args)
      require("CopilotChat").ask(args.args, { selection = require("CopilotChat.select").visual })
    end, { nargs = "*", range = true })
    vim.api.nvim_create_user_command("CopilotChatBuffer", function(args)
      require("CopilotChat").ask(args.args, { selection = require("CopilotChat.select").buffer })
    end, { nargs = "*", range = true })
    vim.api.nvim_create_user_command("CopilotChatInline", function(args)
      require("CopilotChat").ask(args.args, {
        selection = require("CopilotChat.select").visual,
        window = {
          layout = "float",
          relative = "cursor",
          width = 1,
          height = 0.4,
          row = 1,
        },
      })
    end, { nargs = "*", range = true })
  end,
  keys = {
    {
      "<leader>av",
      "<cmd>CopilotChatVisual<cr>",
      mode = "x",
    },
    {
      "<leader>ax",
      "<cmd>CopilotChatInline<cr>",
      mode = "x",
    },
    {
      "<leader>aq",
      function()
        local input = vim.fn.input("Quick Chat: ")
        if input ~= "" then
          vim.cmd("CopilotChatBuffer " .. input)
        end
      end,
    },
    { "<leader>av", "<cmd>CopilotChatToggle<cr>" },
  },
}

**Comment by deathbeam** [comment] 2024-12-05 09:42
Oh i see what is the issue now, thanks for the recording. I will look at this

**Comment by deathbeam** [comment] 2024-12-05 09:58
Ok should be fixed now, can you try @nyanyacoffee

**Closed** 2024-12-05 09:58 UTC
Labels: question
